---
- name: Install Jenkins and Docker on Amazon Linux
  hosts: all
  become: true
  tasks:
    - name: Install Java (required for Jenkins)
      yum:
        name: java-17
        state: present

    - name: Manually add Jenkins repository and import GPG key
      block:
        - name: Add Jenkins Repository File
          copy:
            content: |
              [jenkins]
              name=Jenkins
              baseurl=http://pkg.jenkins.io/redhat-stable
              gpgcheck=1
              gpgkey=https://pkg.jenkins.io/redhat-stable/jenkins.io.key
            dest: /etc/yum.repos.d/jenkins.repo
            mode: 0644

        - name: Import Jenkins GPG Key
          rpm_key:
            key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
            state: present
      when: ansible_distribution_major_version == "2"  # Condition for Amazon Linux 2

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Install Docker prerequisites
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

    - name: Add Docker CE Repository
      yum_repository:
        name: docker-ce
        description: Docker CE Repository
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes

    - name: Install Docker CE
      yum:
        name: docker-ce
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start Jenkins Service
      service:
        name: jenkins
        state: started
        enabled: yes
